abc.bo/src/main/java/kr/co/abcmart/bo/order/model/master/IfOffDealHistory.java
package kr.co.abcmart.bo.order.model.master;

import kr.co.abcmart.bo.order.model.master.base.BaseIfOffDealHistory;
import lombok.Data;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@Data
public class IfOffDealHistory extends BaseIfOffDealHistory {

	// 상품명
	private String prdtName;
	// 매장명
	private String storeName;
	// 매장명
	private Integer orderCnt;
	// 매장명
	private java.math.BigDecimal orderAmt;

	// 회원번호
	private String memberNo;

	// 주문채널
	private String chnnlNo;

	// 거래 번호
	private String orderNo;

	// 기간 검색
	private String orderDateKey;

	/**
	 * 검색기간 from
	 */
	private String fromDate;

	/**
	 * 검색기간 to
	 */
	private String toDate;

	/**
	 * 주문 취소 여부
	 */
	private String chkCancelAll;
	/**
	 * 주문 취소 여부
	 */
	private String chkCancel;

	// 오프라인 매장번호
	private String storeIdText;
}

abc.bo/src/main/java/kr/co/abcmart/bo/order/model/master/IfOrder.java
package kr.co.abcmart.bo.order.model.master;

import kr.co.abcmart.bo.order.model.master.base.BaseIfOrder;

import lombok.Data;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@Data
public class IfOrder extends BaseIfOrder {



}

abc.bo/src/main/java/kr/co/abcmart/bo/order/model/master/OcCashReceipt.java
package kr.co.abcmart.bo.order.model.master;

import kr.co.abcmart.bo.order.model.master.base.BaseOcCashReceipt;

import lombok.Data;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@Data
public class OcCashReceipt extends BaseOcCashReceipt {



}

abc.bo/src/main/java/kr/co/abcmart/bo/order/model/master/OcGiftCardInterlockHistory.java
package kr.co.abcmart.bo.order.model.master;

import kr.co.abcmart.bo.order.model.master.base.BaseOcGiftCardInterlockHistory;

import lombok.Data;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@Data
public class OcGiftCardInterlockHistory extends BaseOcGiftCardInterlockHistory {



}

abc.bo/src/main/java/kr/co/abcmart/bo/order/model/master/OcGiftCardOrder.java
package kr.co.abcmart.bo.order.model.master;

import kr.co.abcmart.bo.order.model.master.base.BaseOcGiftCardOrder;
import kr.co.abcmart.interfaces.module.payment.kcp.model.KcpPaymentApproval;
import lombok.Data;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@Data
public class OcGiftCardOrder extends BaseOcGiftCardOrder {
	// 결제일시
	private String pymntDtm;// PYMNT_DTM
	// 주문 상태 코드
	private String orderStatCodeName;// ORDER_STAT_CODE_NAME

	private String pymntDate;

	private String pymntMeansCode;
	private String kcpPayType;
	private String imageUrl;
	private String historyStartDtm;
	private String historyEndDtm;
	private String pymntAprvNoText;
	/**
	 * kcp결제 모듈에 필요한 객체
	 */
	private KcpPaymentApproval kcpPaymentApproval;

}

abc.bo/src/main/java/kr/co/abcmart/bo/order/model/master/OcGiftCardOrderPayment.java
package kr.co.abcmart.bo.order.model.master;

import kr.co.abcmart.bo.order.model.master.base.BaseOcGiftCardOrderPayment;

import lombok.Data;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@Data
public class OcGiftCardOrderPayment extends BaseOcGiftCardOrderPayment {



}

abc.bo/src/main/java/kr/co/abcmart/bo/order/model/master/OcOfflineBuyHistory.java
package kr.co.abcmart.bo.order.model.master;

import kr.co.abcmart.bo.order.model.master.base.BaseOcOfflineBuyHistory;

import lombok.Data;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@Data
public class OcOfflineBuyHistory extends BaseOcOfflineBuyHistory {



}

abc.bo/src/main/java/kr/co/abcmart/bo/order/model/master/OcOrder.java
package kr.co.abcmart.bo.order.model.master;

import java.util.List;

import kr.co.abcmart.bo.order.model.master.base.BaseOcOrder;
import kr.co.abcmart.common.request.annotation.ParameterOption;
import kr.co.abcmart.common.util.UtilsText;
import kr.co.abcmart.constant.Const;
import kr.co.abcmart.user.LoginManager;
import kr.co.abcmart.util.UtilsMasking;
import lombok.Data;
import lombok.extern.slf4j.Slf4j;

/**
 * @Desc : 주문
 * @FileName : OcOrder.java
 * @Project : abc.bo
 * @Date : 2019. 2. 11.
 * @Author : ljyoung@3top.co.kr
 */
@Slf4j
@Data
public class OcOrder extends BaseOcOrder {

	/**************************************************************
	 * 검색 관련
	 **************************************************************/
	/**
	 * 주문관련 검색 key
	 */
	private String orderSearchKey;

	/**
	 * 주문관련 검색 text, key에 따른 validation check
	 */
	private String orderSearchText;

	/**
	 * 주문상품관련 검색 key
	 */
	private String productSearchKey;

	/**
	 * 주문상품관련 검색 text, key에 따른 validation check
	 */
	private String productSearchText;

	/**
	 * 기간 검색 key
	 */
	private String orderDateKey;

	/**
	 * 검색기간 from
	 */
	private String fromDate;

	/**
	 * 검색기간 to
	 */
	private String toDate;

	/**
	 * 에스크로
	 */
	private String chkEscroTrue;
	private String chkEscroFalse;

	/**
	 * 회원유형
	 */
	private String[] memberTypeCodes;

	/**
	 * 회원등급
	 */
	private String[] mbshpGradeCodes;

	/**
	 * 회원등급
	 */
	private String[] deviceCodes;

	/**
	 * 임직원
	 */
	private String chkMemberTypeERP;

	/**
	 * 주문배송 유형 ( 매장픽업 , 택배 전환 )
	 */
	private String chnnlNo;

	/**
	 * 입점사 코드
	 */
	private String vndrNo;

	/**
	 * 입점사 명
	 */
	private String vndrName;

	/**
	 * 브랜드 번호
	 */
	private String brandNo;

	/**
	 * 브랜드 이름
	 */
	private String brandName;

	/**
	 * 쿠폰 사용 여부
	 */
	private String cpnDscntAmtYn;

	/**
	 * 주문 취소 여부l
	 */
	private String chkCancelAll;

	/**
	 * 회원유형 전체 선택
	 */
	private String chkMemberTypeAll;

	/**
	 * 주문배송상태 전체 선택
	 */
	private String orderPrdtStatCodeAll;

	/**
	 * 결제수단 전체 선택
	 */
	private String chkPaymentAll;

	/**
	 * 발송처 전체 선택
	 */
	private String stockGbnCodeAll;

	/**
	 * 주문 취소 여부
	 */
	private String chkCancel;
	private String optnName;

	/**
	 * 사이트명
	 */
	private String siteName;

	/**
	 * 재고 구분 코드 -- 발송처 ( 검색 )
	 */
	@ParameterOption(target = "stockGbnCode")
	private OcOrderDeliveryHistory[] stockGbnCodeList;
	/**
	 * 주문상품상태코드-- 주문배송상태 ( 검색 )
	 */
	@ParameterOption(target = "orderPrdtStatCode")
	private OcOrderProduct[] orderPrdtStatCodeList;

	/**
	 * 주문상품상태코드-- 결제수단 ( 검색 )
	 */
	@ParameterOption(target = "pymntMeansCode")
	private OcOrderPayment[] pymntMeansCodeList;

	private List<String> authSiteList;

	/**************************************************************
	 * 목록 관련
	 **************************************************************/

	/**
	 * 주문 목록 결제 수단
	 */
	private String pymntMeansCodeName;

	/**
	 * 주문 목록 발송처
	 */
	private String stockGbnCodeName;

	/**
	 * 주문 목록 주문취소여부
	 */
	private String orderCancelFlag;

	/**
	 * 주문 목록 결제 완료일
	 */
	private java.sql.Timestamp pymntDtm;

	/**
	 * 회원명 마스킹 처리
	 */
	public String getUserDpName() {
		String maskingText = "";

		if (null != this.getBuyerName() && null != this.getLoginId()) {
			if (LoginManager.isPersonalInfoManager()) {
				maskingText = UtilsText.concat(this.getLoginId(), Const.L_PAREN, this.getBuyerName(), Const.R_PAREN);
			} else {
				maskingText = UtilsText.concat(UtilsMasking.loginId(this.getLoginId()), Const.L_PAREN,
						UtilsMasking.userName(this.getBuyerName()), Const.R_PAREN);
			}
		}

		return maskingText;
	}

	/**
	 * 그리드 주문자 마스킹 처리
	 */
	public String getBuyerGridName() {
		return UtilsText.concat(UtilsMasking.loginId(this.getLoginId()), Const.L_PAREN,
				UtilsMasking.userName(this.getBuyerName()), Const.R_PAREN);
	}

	/**
	 * 그리드 수령자 마스킹 처리
	 */
	public String getRcvrGridName() {
		return UtilsMasking.userName(this.getRcvrName());
	}

	/**
	 * 수령자명 마스킹 처리
	 */
	public String getRcvrDpName() {
		String maskingText = "";

		if (null != this.getRcvrName()) {
			if (LoginManager.isPersonalInfoManager()) {
				maskingText = this.getRcvrName();
			} else {
				maskingText = UtilsMasking.userName(this.getRcvrName());
			}
		}

		return maskingText;
	}

	/**
	 * 비회원명 마스킹 처리
	 */
	public String getNonUserDpName() {
		String maskingText = "";

		if (null != this.getBuyerName()) {
			if (LoginManager.isPersonalInfoManager()) {
				maskingText = this.getBuyerName();
			} else {
				maskingText = UtilsMasking.userName(this.getBuyerName());
			}
		}

		return maskingText;
	}

	/**
	 * 취소 수량
	 */
	private Long claimCancelCnt;
	/**
	 * 반품 수량
	 */
	private Long claimReturnCnt;
	/**
	 * 교환 수량
	 */
	private Long claimExchangeCnt;

	/**
	 * as 수량
	 */
	private Long claimASCnt;

	/**
	 * 유선상담 갯수
	 */
	// private Long inquiryCnt;

	private Long orderCnt;
	private Long orderAmt;

	// 주문 취소 여부
	private String orderCancelYn;

	/**
	 * 주문번호배열
	 */
	private String[] orderNos;
	private String strOrderNos;

	/**************************************************************
	 * 상세 관련
	 **************************************************************/

	private String memberName;

	private String loginId;

	private String memberTypeCodeName;

	private String mbshpGradeCodeName;

	private String deviceCodeName;

	private String dlvyTypeCodeName;

	private String bankCodeName;

	private String orderStatCodeName;

	private String memBankCode;
	private String memBankAcntTxt;
	private String memBankUserName;
	private String memBankAuth;
	private String memBankAuthNo;
	private String memBankName;

	private Integer productTotCnt;
	private Long cancelPossibleCnt;
	private Long confirmCnt;

	private Long exchangeCnt;
	private Long returnCnt;

	private Long exchangeCancelCnt;
	private Long returnCancelCnt;

	// 취소접수 상품 갯수
	private Long cancelAcceptCnt;
	
	private Long asAcceptCnt;
	private Integer memoTotCnt;
	private Long cancelSumAmt;

	// 적립포인트
	private Integer savePoint;
	// 포인트 적립일시
	private java.sql.Timestamp savepointDtm;
	// 포인트 적립여부
	private String savepointYn;

	private String vaildationType;

	// 배송 id
	private String dlvyIdText;

	// 대시보드 local, vendor 구분
	private String orderType;

	// 자사상품 여부
	private String mmnyPrdtYn;

	// 상품 기준 택배 전환 counting
	private Long logisCnvrtCnt;

	// 휴대전화 뒷자리
	private String buyerHdphnBackNo;

	// 예약 발송일
	private java.sql.Timestamp rsvDlvyDtm;
	
	private Integer[] orderPrdtSeqs;

	/**************************************************************
	 * S : 상세 관련 - 마스킹
	 **************************************************************/

	// 이름
	public String getBuyerName() {

		if (LoginManager.isPersonalInfoManager()) {
			return super.getBuyerName();
		} else {
			return UtilsMasking.userName(super.getBuyerName());
		}
	}

	// 전화번호
	public String getBuyerTelNoText() {

		if (LoginManager.isPersonalInfoManager()) {
			return super.getBuyerTelNoText();
		} else {
			return UtilsMasking.cellPhoneNumber(super.getBuyerTelNoText());
		}
	}

	// 휴대폰번호
	public String getBuyerHdphnNoText() {

		if (LoginManager.isPersonalInfoManager()) {
			return super.getBuyerHdphnNoText();
		} else {
			return UtilsMasking.cellPhoneNumber(super.getBuyerHdphnNoText());
		}
	}

	// 우편주소
	public String getBuyerPostAddrText() {

		if (LoginManager.isPersonalInfoManager()) {
			return super.getBuyerPostAddrText();
		} else {
			return UtilsMasking.postAddress(super.getBuyerPostAddrText());
		}
	}

	// 상세주소
	public String getBuyerDtlAddrText() {

		if (LoginManager.isPersonalInfoManager()) {
			return super.getBuyerDtlAddrText();
		} else {
			return UtilsMasking.postAddress(super.getBuyerDtlAddrText());
		}
	}

	// 주문자 이메일주소
	public String getBuyerEmailAddrText() {

		if (LoginManager.isPersonalInfoManager()) {
			return super.getBuyerEmailAddrText();
		} else {
			return UtilsMasking.emailAddress(super.getBuyerEmailAddrText());
		}
	}

	// 이름
	public String getRcvrName() {

		if (LoginManager.isPersonalInfoManager()) {
			return super.getRcvrName();
		} else {
			return UtilsMasking.userName(super.getRcvrName());
		}
	}

	// 전화번호
	public String getRcvrTelNoText() {

		if (LoginManager.isPersonalInfoManager()) {
			return super.getRcvrTelNoText();
		} else {
			return UtilsMasking.cellPhoneNumber(super.getRcvrTelNoText());
		}
	}

	// 핸드폰
	public String getRcvrHdphnNoText() {

		if (LoginManager.isPersonalInfoManager()) {
			return super.getRcvrHdphnNoText();
		} else {
			return UtilsMasking.cellPhoneNumber(super.getRcvrHdphnNoText());
		}
	}

	// 우편주소
	public String getRcvrPostAddrText() {

		if (LoginManager.isPersonalInfoManager()) {
			return super.getRcvrPostAddrText();
		} else {
			return UtilsMasking.postAddress(super.getRcvrPostAddrText());
		}
	}

	// 상세주소
	public String getRcvrDtlAddrText() {

		if (LoginManager.isPersonalInfoManager()) {
			return super.getRcvrDtlAddrText();
		} else {
			return UtilsMasking.postAddress(super.getRcvrDtlAddrText());
		}
	}

	// 환불계좌
	public String getRfndAcntText() {

		if (LoginManager.isPersonalInfoManager()) {
			return super.getRfndAcntText();
		} else {
			return UtilsMasking.bankAccoutNumber(super.getRfndAcntText());
		}
	}

	// 예금주이름
	public String getAcntHldrName() {

		if (LoginManager.isPersonalInfoManager()) {
			return super.getAcntHldrName();
		} else {
			return UtilsMasking.userName(super.getAcntHldrName());
		}
	}

	// 회원 ID (관리자 ID)
	public String getLoginId() {

		if (LoginManager.isPersonalInfoManager()) {
			return this.loginId;
		} else {
			return UtilsMasking.loginId(this.loginId);
		}
	}


abc.bo/src/main/java/kr/co/abcmart/bo/order/model/master/OcOrderCertificationHistory.java
package kr.co.abcmart.bo.order.model.master;

import kr.co.abcmart.bo.order.model.master.base.BaseOcOrderCertificationHistory;

import lombok.Data;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@Data
public class OcOrderCertificationHistory extends BaseOcOrderCertificationHistory {



}

abc.bo/src/main/java/kr/co/abcmart/bo/order/model/master/OcOrderConvenienceStore.java
package kr.co.abcmart.bo.order.model.master;

import kr.co.abcmart.bo.order.model.master.base.BaseOcOrderConvenienceStore;
import lombok.Data;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@Data
public class OcOrderConvenienceStore extends BaseOcOrderConvenienceStore {
	/**
	 * 
	 * 설명 : 편의점 코드
	 */
	private String hoCode;

}

abc.bo/src/main/java/kr/co/abcmart/bo/order/model/master/OcOrderCrtfcHistory.java
package kr.co.abcmart.bo.order.model.master;

import kr.co.abcmart.bo.order.model.master.base.BaseOcOrderCrtfcHistory;

import lombok.Data;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@Data
public class OcOrderCrtfcHistory extends BaseOcOrderCrtfcHistory {



}

abc.bo/src/main/java/kr/co/abcmart/bo/order/model/master/OcOrderDeliveryAlertHistory.java
package kr.co.abcmart.bo.order.model.master;

import kr.co.abcmart.bo.order.model.master.base.BaseOcOrderDeliveryAlertHistory;

import lombok.Data;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@Data
public class OcOrderDeliveryAlertHistory extends BaseOcOrderDeliveryAlertHistory {



}

abc.bo/src/main/java/kr/co/abcmart/bo/order/model/master/OcOrderDeliveryChangeHistory.java
package kr.co.abcmart.bo.order.model.master;

import kr.co.abcmart.bo.order.model.master.base.BaseOcOrderDeliveryChangeHistory;
import lombok.Data;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@Data
public class OcOrderDeliveryChangeHistory extends BaseOcOrderDeliveryChangeHistory {

}

abc.bo/src/main/java/kr/co/abcmart/bo/order/model/master/OcOrderDeliveryHistory.java
package kr.co.abcmart.bo.order.model.master;

import kr.co.abcmart.bo.order.model.master.base.BaseOcOrderDeliveryHistory;
import lombok.Data;
import lombok.ToString;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@Data
@ToString(callSuper = true)
public class OcOrderDeliveryHistory extends BaseOcOrderDeliveryHistory {

	private String stockGbnCodeName;

	private String logisVndrCodeName;

	private String dlvyDscntcRsnCodeName;

	private String missProcTypeCodeName;

	private String dlvyStatCodeName;

	/**
	 * 배송상태 - 변경전
	 */
	private String dlvyStatCodeBefore;

	/**
	 * 상품 배송 상태
	 */
	private String orderPrdtStatCode;

	/**
	 * 배송상태 - 변경 후
	 */
	private String dlvyStatCode;

	/**
	 * 주문번호 배열
	 */
	private String[] orderNos;

	/**
	 * 로그인ID
	 */
	private String loginId;

	/**
	 * 관리자 명
	 */
	private String adminName;

	/**
	 * 배송아이디 배열
	 */
	private String[] dlvyIdTextArr = null;

	/**
	 * 업체 상품 코드
	 */
	private String vndrPrdtNoText;

	/**
	 * 상품 코드
	 */
	private String prdtNo;

	/**
	 * 설명 : 조건절 배송상태코드
	 */
	private String whereDlvyStatCode;

	/**
	 * 재배송 처리시 원 재고구분 코드
	 */
	private String orgStockGbnCode;

	private String cbcd;

	/**
	 * 상품 옵션 코드
	 */
	private String prdtOptnNo;
	/**
	 * 상품 타입
	 */
	private String prdtTypeCode;

	/**
	 * 상위주문상품순번
	 */
	private java.lang.Integer upOrderPrdtSeq;

	/**
	 * 매장명
	 */
	private String storeName;

	// 상태
	private String status;

	// 체크박스 체크 여부
	private java.lang.Integer checkedRows;
	
	//처리구분 코드
	private String procGubnCode; 

}

abc.bo/src/main/java/kr/co/abcmart/bo/order/model/master/OcOrderMemo.java
package kr.co.abcmart.bo.order.model.master;

import kr.co.abcmart.bo.order.model.master.base.BaseOcOrderMemo;
import lombok.Data;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@Data
public class OcOrderMemo extends BaseOcOrderMemo {

	private String memoGbn;

	private String adminId;

	private String adminName;

}

abc.bo/src/main/webapp/WEB-INF/views/order/cvsResult.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<ui:decorator name="none"/>
<!DOCTYPE html>
<html>
<head>
<script type="text/javascript">
// 편의점 결과 정보
var cvsResult = {"store_code"     : "${store_code}",
                 "ho_code"        : "${ho_code}" ,
                 "store_address1" : "${store_address1}",
                 "store_address2" : "${store_address2}",
                 "post_no"        : "${post_no}",
                 "code_f"         : "${code_f}",
                 "dd_zone"        : "${dd_zone}",
                 "dd_bag"         : "${dd_bag}",
                 "codePany"       : "${codePany}",
                 "codeName"       : "${codeName}",
                 "codeTel"        : "${codeTel}",
                 "eupmyeon"       : "${eupmyeon}"
                 };
opener.opener.setCVSResult(cvsResult);  // 주문서작성페이지의 값 return
window.close();        //현재화면(팝업2) 닫음 setCVSResult
opener.window.close(); //팝업1 닫음 
</script>
</head>
<body>
</body>
</html>

abc.bo/src/main/webapp/WEB-INF/views/order/kakaoPay-history-pop.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@include file="/WEB-INF/views/common/subHeader.jsp" %>
<script type="text/javascript">
	$(function() {
		
		abc.biz.order.info.tab.kakaoPay.initKakaoPayGrid();  		// abc 자사 상품
		
	});
	
	// 결제정보 영역
	function kakaoPaySheet_OnRowSearchEnd(row){ 
		var paymentMethodTypeView 	= kakaoPaySheet.GetCellValue(row, "paymentMethodTypeView");
		var cardBinView 			= kakaoPaySheet.GetCellValue(row, "cardBinView");
		var installMonthView 		= kakaoPaySheet.GetCellValue(row, "installMonthView");
		var cardCorpNameView 		= kakaoPaySheet.GetCellValue(row, "cardCorpNameView");
		var interestFreeInstallView = kakaoPaySheet.GetCellValue(row, "interestFreeInstallView");
		
		var payInfo = "-";
		var installMonthText = "";
		var installMonth = installMonthView <= 1 ? "일시불" : installMonthView ; 
		
		if ( paymentMethodTypeView ==  "CARD") { // 카드
			if (interestFreeInstallView = "Y") { // 무이자 
				installMonthText = "(무이자)" ;
			}else { // 유이자 
				installMonthText = "("+ installMonth +")" ;
			}
			payInfo = cardCorpNameView + " " + cardBinView +" "+ installMonthText ; 
			
		}else if (paymentMethodTypeView ==  "MONEY") { // 
			payInfo = "카카오페이";
		}
		kakaoPaySheet.SetCellValue(row, "payInfo", payInfo);
		kakaoPaySheet.SetCellValue(row, "status", ""); // HTML로 재조합하여 데이터를 조회하면 기본 상태가 "수정"으로 인식되어, 조회 시 강제로 빈값 처리
	}
	
</script>
<body class="window-body">
	<form id="frmSearch" name="frmSearch" method="post" onsubmit="return false;">
		<input type="hidden" id="orderNo" name="orderNo" value='${orderNo}'>
		<input type="hidden" id="siteNo" name="siteNo" value='${siteNo}'>
		<input type="hidden" id="tid" name="tid"  value='${tid}'>
	</form>
	<div class="window-wrap">
		<div class="window-title">
			<h1>카카오페이 결제내역</h1>
		</div>
		<div class="window-content">
			<!-- S : content-header -->
			<div class="content-header">
				<div class="fl">
					<h3 class="content-title">[주문번호 <span>${orderNo}</span>] 카카오페이 결제내역</h3>
				</div>
			</div>
			<!-- E : content-header -->

			<!-- S : ibsheet-wrap -->
			<div class="ibsheet-wrap">
				<div style="width:100%; height:429px;" id="kakaoPayGrid">
				</div>
			</div>
			<!-- E : ibsheet-wrap -->
		</div>
	</div>
</body>
<script src="/static/common/js/biz/order/abcmart.order.info.tab.kakaopay.js<%=_DP_REV%>"></script>
</html>

abc.bo/src/main/webapp/WEB-INF/views/order/password-change-pop.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@include file="/WEB-INF/views/common/subHeader.jsp" %>

<script type="text/javascript">
	
</script>

<body class="window-body">
<form id="orderForm" name="orderForm" method="post" onsubmit="return false;">
<input type="hidden" id="orderNo" name="orderNo" value='<c:out value="${orderDtail.orderNo}"/>'>
<input type="hidden" id="OldPswdText" name="OldPswdText" value='<c:out value="${orderDtail.nmbrCrtfcNoText}"/>'>
	<div class="window-wrap">
		<div class="window-title">
			<h1>${orderDtail.buyerName}님 주문 비밀번호 변경</h1>
		</div>
		<div class="window-content">

			<!-- S : content-header -->
			<div class="content-header">
				<div class="fl">
					<h3 class="content-title">주문자 정보</h3>
				</div>
			</div>
			<!-- E : content-header -->

			<!-- S : tbl-row -->
			<table class="tbl-row">
				<caption>주문자 정보</caption>
				<colgroup>
					<col style="width: 140px;">
					<col>
				</colgroup>
				<tbody>
					<tr>
						<th scope="row">주문번호</th>
						<td>${orderDtail.orderNo}</td>
					</tr>
					<tr>
						<th scope="row">이메일</th>
						<td>${orderDtail.buyerEmailAddrText}</td>
					</tr>
				</tbody>
			</table>
			<!-- E : tbl-row -->

			<!-- S : content-header -->
			<div class="content-header">
				<div class="fl">
					<h3 class="content-title">비밀번호 변경</h3>
				</div>
			</div>
			<!-- E : content-header -->

			<!-- S : tbl-row -->
			<table class="tbl-row">
				<caption>비밀번호 변경</caption>
				<colgroup>
					<col style="width: 140px;">
					<col>
				</colgroup>
				<tbody>
					<tr>
						<th scope="row">비밀번호 입력</th>
						<td class="input">
							<input type="password" class="ui-input" title="비밀번호 입력" id="pswdText" name="pswdText" placeholder="6자리입력" maxlength="6">
						</td>
					</tr>
					<tr>
						<th scope="row">비밀번호 재입력</th>
						<td class="input">
							<input type="password" class="ui-input" title="비밀번호 입력" id="pswdTextConfirm" name="pswdTextConfirm" placeholder="6자리입력" maxlength="6">
						</td>
					</tr>
				</tbody>
			</table>
			<!-- E : tbl-row -->

			<!-- S : window-btn-group -->
			<div class="window-btn-group">
				<a href="#" class="btn-normal btn-link" id="passwordSave">확인</a>
			</div>
			<!-- E : window-btn-group -->
		</div>
	</div>
</form>	
</body>

<script src="/static/common/js/biz/order/abcmart.order.nonCustPassword.js<%=_DP_REV%>"></script>